version: '3'
services:
  mopp_chat_server:
    image: ghcr.io/morse-code-over-ip/chatserver-mopp-udp:sha-da06e4a
    #build: .
    container_name: mopp_chat_server
    ports: 
      - 7373:7373/udp
    restart: always
    volumes:
      - "logfile:/app/logfile.txt"
  frontail:
    restart: unless-stopped
    image: ghcr.io/8ch9azbsfifz/frontail:latest
    command: /opt/log/logfile.txt
    depends_on:
      - mopp_chat_server
    volumes:
      - "logfile:/opt/log/logfile.txt"
    ports:
      - "8001:9001"
volumes:
  logfile: