version: '3'
services:
 mopp_chat_server:
  image: ghcr.io/morse-code-over-ip/chatserver-mopp-udp:latest
  #build: .
  container_name: mopp_chat_server
  ports: 
    - 7373:7373/udp
  restart: always

