version: '3'
services:
  mopp_chat_server:
    image: ghcr.io/morse-code-over-ip/chatserver-mopp-udp:latest
    #build: . # use this instead of image, if you do not want to use the gchr.io repo
    container_name: mopp_chat_server
    ports: 
      - 7373:7373/udp
    restart: always
    volumes:
      - "logfile:/app/logs"
  frontail:
    restart: unless-stopped
    image: ghcr.io/8ch9azbsfifz/frontail:latest
    command: /opt/log/logfile.txt
    depends_on:
      - mopp_chat_server
    volumes:
      - "logfile:/opt/log"
    ports:
      - "8001:9001"
volumes:
  logfile: